server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 58.87.67.162
    port: 7000
    password: Yakai2018@
    database: 0
    jedis:
      pool:
        #最大连接数（负值表示没有限制）
        max-active: 100
        #最大空闲链接
        max-idle: 10
        #最小空闲链接
        min-idle: 5
        #最大阻塞时间 负值表示不限制
        max-wait: -1ms

redis-limit-lua: |
  local c = redis.call('INCR', KEYS[1])
  if tonumber(c) == 1 then
    redis.call('expire', KEYS[1], ARGV[1])
    return 1
  elseif tonumber(c) > tonumber(ARGV[2]) then
    return 0
  else
    return 1
  end
